insert into OperatorType (ID, Name) values (38, 'Equal');
insert into OperatorType (ID, Name) values (39, 'NotEqual');
insert into OperatorType (ID, Name) values (40, 'LessThan');
insert into OperatorType (ID, Name) values (41, 'GreaterThan');
insert into OperatorType (ID, Name) values (42, 'LessThanOrEqual');
insert into OperatorType (ID, Name) values (43, 'GreaterThanOrEqual');
insert into OperatorType (ID, Name) values (44, 'And');
insert into OperatorType (ID, Name) values (45, 'Or');
insert into OperatorType (ID, Name) values (46, 'Not');
