CREATE TABLE [dbo].[MidiMapping](
	[ID] [int] NOT NULL,
	[Name] [nvarchar](256) NULL,
	[DocumentID] [int] NOT NULL,
 CONSTRAINT [PK_MidiMapping] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
