alter table MidiMapping drop column FromMidiControllerValue
alter table MidiMapping drop column TillMidiControllerValue
alter table MidiMapping drop column FromMidiNoteNumber
alter table MidiMapping drop column TillMidiNoteNumber
alter table MidiMapping drop column FromMidiVelocity
alter table MidiMapping drop column TillMidiVelocity
alter table MidiMapping drop column FromPosition
alter table MidiMapping drop column TillPosition
alter table MidiMapping drop column FromToneNumber
alter table MidiMapping drop column TillToneNumber
