//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Business.Synthesizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JJ.Business.Synthesizer.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve &apos;{0}&apos; cannot be deleted, because it is being used by operators..
        /// </summary>
        internal static string CannotDeleteCurveBecauseHasOperators {
            get {
                return ResourceManager.GetString("CannotDeleteCurveBecauseHasOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch &apos;{0}&apos; cannot be deleted, because it is the main patch of the document..
        /// </summary>
        internal static string CannotDeletePatchBecauseIsMainPatch {
            get {
                return ResourceManager.GetString("CannotDeletePatchBecauseIsMainPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample &apos;{0}&apos; cannot be deleted, because it is being used by operators..
        /// </summary>
        internal static string CannotDeleteSampleBecauseHasOperators {
            get {
                return ResourceManager.GetString("CannotDeleteSampleBecauseHasOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel count does not match speaker setup..
        /// </summary>
        internal static string ChannelCountDoesNotMatchSpeakerSetup {
            get {
                return ResourceManager.GetString("ChannelCountDoesNotMatchSpeakerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel number does not match speaker setup..
        /// </summary>
        internal static string ChannelIndexNumberDoesNotMatchSpeakerSetup {
            get {
                return ResourceManager.GetString("ChannelIndexNumberDoesNotMatchSpeakerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos; is dependent on document &apos;{1}&apos;..
        /// </summary>
        internal static string DocumentIsDependentOnDocument {
            get {
                return ResourceManager.GetString("DocumentIsDependentOnDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} operator named &apos;{1}&apos; does not have {2} filled in..
        /// </summary>
        internal static string InletNotSet {
            get {
                return ResourceManager.GetString("InletNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplifier of &apos;{0}&apos; named &apos;{1}&apos; is 0..
        /// </summary>
        internal static string ObjectAmplifier0 {
            get {
                return ResourceManager.GetString("ObjectAmplifier0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator named &apos;{0}&apos; has a circular reference..
        /// </summary>
        internal static string OperatorIsCircular {
            get {
                return ResourceManager.GetString("OperatorIsCircular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patch of operator &apos;{0}&apos; is filled in, but it is not the expected patch &apos;{1}&apos;..
        /// </summary>
        internal static string OperatorPatchIsNotTheExpectedPatch {
            get {
                return ResourceManager.GetString("OperatorPatchIsNotTheExpectedPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample &apos;{0}&apos; has no data..
        /// </summary>
        internal static string SampleCount0 {
            get {
                return ResourceManager.GetString("SampleCount0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample named &apos;{0}&apos; is not active..
        /// </summary>
        internal static string SampleNotActive {
            get {
                return ResourceManager.GetString("SampleNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample &apos;{0}&apos; is not loaded..
        /// </summary>
        internal static string SampleNotLoaded {
            get {
                return ResourceManager.GetString("SampleNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string UnsupportedOperatorTypeEnumValue {
            get {
                return ResourceManager.GetString("UnsupportedOperatorTypeEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value named &apos;{0}&apos; is 0..
        /// </summary>
        internal static string ValueIs0WithName {
            get {
                return ResourceManager.GetString("ValueIs0WithName", resourceCulture);
            }
        }
    }
}
