//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJ.Business.Synthesizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JJ.Business.Synthesizer.Resources.PropertyDisplayNames", typeof(PropertyDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute.
        /// </summary>
        public static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pass Filter.
        /// </summary>
        public static string AllPassFilter {
            get {
                return ResourceManager.GetString("AllPassFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplifier.
        /// </summary>
        public static string Amplifier {
            get {
                return ResourceManager.GetString("Amplifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Duration.
        /// </summary>
        public static string AttackDuration {
            get {
                return ResourceManager.GetString("AttackDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File Format.
        /// </summary>
        public static string AudioFileFormat {
            get {
                return ResourceManager.GetString("AudioFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File Output.
        /// </summary>
        public static string AudioFileOutput {
            get {
                return ResourceManager.GetString("AudioFileOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File Output List.
        /// </summary>
        public static string AudioFileOutputList {
            get {
                return ResourceManager.GetString("AudioFileOutputList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Output.
        /// </summary>
        public static string AudioOutput {
            get {
                return ResourceManager.GetString("AudioOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Follower.
        /// </summary>
        public static string AverageFollower {
            get {
                return ResourceManager.GetString("AverageFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average over Dimension.
        /// </summary>
        public static string AverageOverDimension {
            get {
                return ResourceManager.GetString("AverageOverDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average over Inlets.
        /// </summary>
        public static string AverageOverInlets {
            get {
                return ResourceManager.GetString("AverageOverInlets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band Pass Filter, Constant Peak Gain.
        /// </summary>
        public static string BandPassFilterConstantPeakGain {
            get {
                return ResourceManager.GetString("BandPassFilterConstantPeakGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band Pass Filter, Constant Transition Gain.
        /// </summary>
        public static string BandPassFilterConstantTransitionGain {
            get {
                return ResourceManager.GetString("BandPassFilterConstantTransitionGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band Width.
        /// </summary>
        public static string BandWidth {
            get {
                return ResourceManager.GetString("BandWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Frequency.
        /// </summary>
        public static string BaseFrequency {
            get {
                return ResourceManager.GetString("BaseFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Modulation Depth.
        /// </summary>
        public static string BrightnessModulationDepth {
            get {
                return ResourceManager.GetString("BrightnessModulationDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Modulation Speed.
        /// </summary>
        public static string BrightnessModulationSpeed {
            get {
                return ResourceManager.GetString("BrightnessModulationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle.
        /// </summary>
        public static string Bundle {
            get {
                return ResourceManager.GetString("Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-Bit.
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes to Skip.
        /// </summary>
        public static string BytesToSkip {
            get {
                return ResourceManager.GetString("BytesToSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        public static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cent.
        /// </summary>
        public static string Cent {
            get {
                return ResourceManager.GetString("Cent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Frequency.
        /// </summary>
        public static string CenterFrequency {
            get {
                return ResourceManager.GetString("CenterFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cents.
        /// </summary>
        public static string Cents {
            get {
                return ResourceManager.GetString("Cents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Trigger.
        /// </summary>
        public static string ChangeTrigger {
            get {
                return ResourceManager.GetString("ChangeTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closest over Dimension.
        /// </summary>
        public static string ClosestOverDimension {
            get {
                return ResourceManager.GetString("ClosestOverDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closest over Dimension Exp.
        /// </summary>
        public static string ClosestOverDimensionExp {
            get {
                return ResourceManager.GetString("ClosestOverDimensionExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closest over Inlets.
        /// </summary>
        public static string ClosestOverInlets {
            get {
                return ResourceManager.GetString("ClosestOverInlets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closest over Inlets Exp.
        /// </summary>
        public static string ClosestOverInletsExp {
            get {
                return ResourceManager.GetString("ClosestOverInletsExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Recalculation.
        /// </summary>
        public static string CollectionRecalculation {
            get {
                return ResourceManager.GetString("CollectionRecalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        public static string Continuous {
            get {
                return ResourceManager.GetString("Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic.
        /// </summary>
        public static string Cubic {
            get {
                return ResourceManager.GetString("Cubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic Abrupt Slope.
        /// </summary>
        public static string CubicAbruptSlope {
            get {
                return ResourceManager.GetString("CubicAbruptSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic Equidistant.
        /// </summary>
        public static string CubicEquidistant {
            get {
                return ResourceManager.GetString("CubicEquidistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic Smooth Slope.
        /// </summary>
        public static string CubicSmoothSlope {
            get {
                return ResourceManager.GetString("CubicSmoothSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve.
        /// </summary>
        public static string Curve {
            get {
                return ResourceManager.GetString("Curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve ID.
        /// </summary>
        public static string CurveID {
            get {
                return ResourceManager.GetString("CurveID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curves.
        /// </summary>
        public static string Curves {
            get {
                return ResourceManager.GetString("Curves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Dimension Name.
        /// </summary>
        public static string CustomDimensionName {
            get {
                return ResourceManager.GetString("CustomDimensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Operator.
        /// </summary>
        public static string CustomOperator {
            get {
                return ResourceManager.GetString("CustomOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Key.
        /// </summary>
        public static string DataKey {
            get {
                return ResourceManager.GetString("DataKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Keys.
        /// </summary>
        public static string DataKeys {
            get {
                return ResourceManager.GetString("DataKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dB Gain.
        /// </summary>
        public static string DBGain {
            get {
                return ResourceManager.GetString("DBGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay Duration.
        /// </summary>
        public static string DecayDuration {
            get {
                return ResourceManager.GetString("DecayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominator.
        /// </summary>
        public static string Denominator {
            get {
                return ResourceManager.GetString("Denominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Buffer Size (sec.).
        /// </summary>
        public static string DesiredBufferDuration {
            get {
                return ResourceManager.GetString("DesiredBufferDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        public static string Dimension {
            get {
                return ResourceManager.GetString("Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension to Outlets.
        /// </summary>
        public static string DimensionToOutlets {
            get {
                return ResourceManager.GetString("DimensionToOutlets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÷.
        /// </summary>
        public static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Else.
        /// </summary>
        public static string Else {
            get {
                return ResourceManager.GetString("Else", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponent.
        /// </summary>
        public static string Exponent {
            get {
                return ResourceManager.GetString("Exponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponents.
        /// </summary>
        public static string Exponents {
            get {
                return ResourceManager.GetString("Exponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string Factor {
            get {
                return ResourceManager.GetString("Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factors.
        /// </summary>
        public static string Factors {
            get {
                return ResourceManager.GetString("Factors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequencies.
        /// </summary>
        public static string Frequencies {
            get {
                return ResourceManager.GetString("Frequencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Frequencies.
        /// </summary>
        public static string FrequencyCount {
            get {
                return ResourceManager.GetString("FrequencyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Dimension.
        /// </summary>
        public static string GetDimension {
            get {
                return ResourceManager.GetString("GetDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        public static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic.
        /// </summary>
        public static string Harmonic {
            get {
                return ResourceManager.GetString("Harmonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hermite.
        /// </summary>
        public static string Hermite {
            get {
                return ResourceManager.GetString("Hermite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Pass Filter.
        /// </summary>
        public static string HighPassFilter {
            get {
                return ResourceManager.GetString("HighPassFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Shelf Filter.
        /// </summary>
        public static string HighShelfFilter {
            get {
                return ResourceManager.GetString("HighShelfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        public static string If {
            get {
                return ResourceManager.GetString("If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet.
        /// </summary>
        public static string Inlet {
            get {
                return ResourceManager.GetString("Inlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlets.
        /// </summary>
        public static string Inlets {
            get {
                return ResourceManager.GetString("Inlets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlets to Dimension.
        /// </summary>
        public static string InletsToDimension {
            get {
                return ResourceManager.GetString("InletsToDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-Bit.
        /// </summary>
        public static string Int16 {
            get {
                return ResourceManager.GetString("Int16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string Intensity {
            get {
                return ResourceManager.GetString("Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity Modulation Depth.
        /// </summary>
        public static string IntensityModulationDepth {
            get {
                return ResourceManager.GetString("IntensityModulationDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity Modulation Speed.
        /// </summary>
        public static string IntensityModulationSpeed {
            get {
                return ResourceManager.GetString("IntensityModulationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolate.
        /// </summary>
        public static string Interpolate {
            get {
                return ResourceManager.GetString("Interpolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation.
        /// </summary>
        public static string Interpolation {
            get {
                return ResourceManager.GetString("Interpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation Type.
        /// </summary>
        public static string InterpolationType {
            get {
                return ResourceManager.GetString("InterpolationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete.
        /// </summary>
        public static string IsObsolete {
            get {
                return ResourceManager.GetString("IsObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        public static string LessThanOrEqual {
            get {
                return ResourceManager.GetString("LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Remember T0.
        /// </summary>
        public static string LineRememberT0 {
            get {
                return ResourceManager.GetString("LineRememberT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Remember T1.
        /// </summary>
        public static string LineRememberT1 {
            get {
                return ResourceManager.GetString("LineRememberT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number (when we start counting at 0).
        /// </summary>
        public static string ListIndex {
            get {
                return ResourceManager.GetString("ListIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal Frequencies.
        /// </summary>
        public static string LiteralFrequencies {
            get {
                return ResourceManager.GetString("LiteralFrequencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal Frequency.
        /// </summary>
        public static string LiteralFrequency {
            get {
                return ResourceManager.GetString("LiteralFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        public static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop End Marker.
        /// </summary>
        public static string LoopEndMarker {
            get {
                return ResourceManager.GetString("LoopEndMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Start Marker.
        /// </summary>
        public static string LoopStartMarker {
            get {
                return ResourceManager.GetString("LoopStartMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Pass Filter.
        /// </summary>
        public static string LowPassFilter {
            get {
                return ResourceManager.GetString("LowPassFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Shelf Filter.
        /// </summary>
        public static string LowShelfFilter {
            get {
                return ResourceManager.GetString("LowShelfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent Notes.
        /// </summary>
        public static string MaxConcurrentNotes {
            get {
                return ResourceManager.GetString("MaxConcurrentNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Follower.
        /// </summary>
        public static string MaxFollower {
            get {
                return ResourceManager.GetString("MaxFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Frequency.
        /// </summary>
        public static string MaxFrequency {
            get {
                return ResourceManager.GetString("MaxFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max over Dimension.
        /// </summary>
        public static string MaxOverDimension {
            get {
                return ResourceManager.GetString("MaxOverDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max over Inlets.
        /// </summary>
        public static string MaxOverInlets {
            get {
                return ResourceManager.GetString("MaxOverInlets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Follower.
        /// </summary>
        public static string MinFollower {
            get {
                return ResourceManager.GetString("MinFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Frequency.
        /// </summary>
        public static string MinFrequency {
            get {
                return ResourceManager.GetString("MinFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min over Dimension.
        /// </summary>
        public static string MinOverDimension {
            get {
                return ResourceManager.GetString("MinOverDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min over Inlets.
        /// </summary>
        public static string MinOverInlets {
            get {
                return ResourceManager.GetString("MinOverInlets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        public static string Mono {
            get {
                return ResourceManager.GetString("Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ×.
        /// </summary>
        public static string Multiply {
            get {
                return ResourceManager.GetString("Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to × (with origin).
        /// </summary>
        public static string MultiplyWithOrigin {
            get {
                return ResourceManager.GetString("MultiplyWithOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        public static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes.
        /// </summary>
        public static string Nodes {
            get {
                return ResourceManager.GetString("Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Type.
        /// </summary>
        public static string NodeType {
            get {
                return ResourceManager.GetString("NodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise.
        /// </summary>
        public static string Noise {
            get {
                return ResourceManager.GetString("Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notch Filter.
        /// </summary>
        public static string NotchFilter {
            get {
                return ResourceManager.GetString("NotchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Duration.
        /// </summary>
        public static string NoteDuration {
            get {
                return ResourceManager.GetString("NoteDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt;.
        /// </summary>
        public static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Start.
        /// </summary>
        public static string NoteStart {
            get {
                return ResourceManager.GetString("NoteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerator.
        /// </summary>
        public static string Numerator {
            get {
                return ResourceManager.GetString("Numerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave.
        /// </summary>
        public static string Octave {
            get {
                return ResourceManager.GetString("Octave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/x.
        /// </summary>
        public static string OneOverX {
            get {
                return ResourceManager.GetString("OneOverX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand.
        /// </summary>
        public static string Operand {
            get {
                return ResourceManager.GetString("Operand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Type.
        /// </summary>
        public static string OperatorType {
            get {
                return ResourceManager.GetString("OperatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Type.
        /// </summary>
        public static string OperatorTypeName {
            get {
                return ResourceManager.GetString("OperatorTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Location.
        /// </summary>
        public static string OriginalLocation {
            get {
                return ResourceManager.GetString("OriginalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet.
        /// </summary>
        public static string Outlet {
            get {
                return ResourceManager.GetString("Outlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlets.
        /// </summary>
        public static string Outlets {
            get {
                return ResourceManager.GetString("Outlets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet Type.
        /// </summary>
        public static string OutletType {
            get {
                return ResourceManager.GetString("OutletType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passthrough.
        /// </summary>
        public static string PassThrough {
            get {
                return ResourceManager.GetString("PassThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch.
        /// </summary>
        public static string Patch {
            get {
                return ResourceManager.GetString("Patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patches.
        /// </summary>
        public static string Patches {
            get {
                return ResourceManager.GetString("Patches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet.
        /// </summary>
        public static string PatchInlet {
            get {
                return ResourceManager.GetString("PatchInlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet.
        /// </summary>
        public static string PatchOutlet {
            get {
                return ResourceManager.GetString("PatchOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peaking EQ Filter.
        /// </summary>
        public static string PeakingEQFilter {
            get {
                return ResourceManager.GetString("PeakingEQFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        public static string Pulse {
            get {
                return ResourceManager.GetString("Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Trigger.
        /// </summary>
        public static string PulseTrigger {
            get {
                return ResourceManager.GetString("PulseTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range over Dimension.
        /// </summary>
        public static string RangeOverDimension {
            get {
                return ResourceManager.GetString("RangeOverDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAW File.
        /// </summary>
        public static string Raw {
            get {
                return ResourceManager.GetString("Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        public static string ReferencedDocuments {
            get {
                return ResourceManager.GetString("ReferencedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Duration.
        /// </summary>
        public static string ReleaseDuration {
            get {
                return ResourceManager.GetString("ReleaseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release End Marker.
        /// </summary>
        public static string ReleaseEndMarker {
            get {
                return ResourceManager.GetString("ReleaseEndMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Count.
        /// </summary>
        public static string SampleCount {
            get {
                return ResourceManager.GetString("SampleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Data Type.
        /// </summary>
        public static string SampleDataType {
            get {
                return ResourceManager.GetString("SampleDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample ID.
        /// </summary>
        public static string SampleID {
            get {
                return ResourceManager.GetString("SampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Rate.
        /// </summary>
        public static string SamplingRate {
            get {
                return ResourceManager.GetString("SamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saw Down.
        /// </summary>
        public static string SawDown {
            get {
                return ResourceManager.GetString("SawDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saw Up.
        /// </summary>
        public static string SawUp {
            get {
                return ResourceManager.GetString("SawUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaler.
        /// </summary>
        public static string Scaler {
            get {
                return ResourceManager.GetString("Scaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scales.
        /// </summary>
        public static string Scales {
            get {
                return ResourceManager.GetString("Scales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Type.
        /// </summary>
        public static string ScaleType {
            get {
                return ResourceManager.GetString("ScaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semitone.
        /// </summary>
        public static string SemiTone {
            get {
                return ResourceManager.GetString("SemiTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semitones.
        /// </summary>
        public static string SemiTones {
            get {
                return ResourceManager.GetString("SemiTones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Dimension.
        /// </summary>
        public static string SetDimension {
            get {
                return ResourceManager.GetString("SetDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        public static string Signal {
            get {
                return ResourceManager.GetString("Signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine.
        /// </summary>
        public static string Sine {
            get {
                return ResourceManager.GetString("Sine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slice Length.
        /// </summary>
        public static string SliceLength {
            get {
                return ResourceManager.GetString("SliceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort over Dimension.
        /// </summary>
        public static string SortOverDimension {
            get {
                return ResourceManager.GetString("SortOverDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort over Inlets.
        /// </summary>
        public static string SortOverInlets {
            get {
                return ResourceManager.GetString("SortOverInlets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Value A.
        /// </summary>
        public static string SourceValueA {
            get {
                return ResourceManager.GetString("SourceValueA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Value B.
        /// </summary>
        public static string SourceValueB {
            get {
                return ResourceManager.GetString("SourceValueB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker Setup.
        /// </summary>
        public static string SpeakerSetup {
            get {
                return ResourceManager.GetString("SpeakerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum.
        /// </summary>
        public static string Spectrum {
            get {
                return ResourceManager.GetString("Spectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squash.
        /// </summary>
        public static string Squash {
            get {
                return ResourceManager.GetString("Squash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Dimension.
        /// </summary>
        public static string StandardDimension {
            get {
                return ResourceManager.GetString("StandardDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        public static string Stereo {
            get {
                return ResourceManager.GetString("Stereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        public static string Stretch {
            get {
                return ResourceManager.GetString("Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stripe.
        /// </summary>
        public static string Stripe {
            get {
                return ResourceManager.GetString("Stripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to –.
        /// </summary>
        public static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Follower.
        /// </summary>
        public static string SumFollower {
            get {
                return ResourceManager.GetString("SumFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum over Dimension.
        /// </summary>
        public static string SumOverDimension {
            get {
                return ResourceManager.GetString("SumOverDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustain Volume.
        /// </summary>
        public static string SustainVolume {
            get {
                return ResourceManager.GetString("SustainVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Value A.
        /// </summary>
        public static string TargetValueA {
            get {
                return ResourceManager.GetString("TargetValueA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Value B.
        /// </summary>
        public static string TargetValueB {
            get {
                return ResourceManager.GetString("TargetValueB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then.
        /// </summary>
        public static string Then {
            get {
                return ResourceManager.GetString("Then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        public static string Till {
            get {
                return ResourceManager.GetString("Till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Multiplier.
        /// </summary>
        public static string TimeMultiplier {
            get {
                return ResourceManager.GetString("TimeMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Exponent.
        /// </summary>
        public static string TimePower {
            get {
                return ResourceManager.GetString("TimePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Trigger.
        /// </summary>
        public static string ToggleTrigger {
            get {
                return ResourceManager.GetString("ToggleTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone.
        /// </summary>
        public static string Tone {
            get {
                return ResourceManager.GetString("Tone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone Count.
        /// </summary>
        public static string ToneCount {
            get {
                return ResourceManager.GetString("ToneCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tones.
        /// </summary>
        public static string Tones {
            get {
                return ResourceManager.GetString("Tones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Frequency.
        /// </summary>
        public static string TransitionFrequency {
            get {
                return ResourceManager.GetString("TransitionFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Slope.
        /// </summary>
        public static string TransitionSlope {
            get {
                return ResourceManager.GetString("TransitionSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tremolo Depth.
        /// </summary>
        public static string TremoloDepth {
            get {
                return ResourceManager.GetString("TremoloDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tremolo Speed.
        /// </summary>
        public static string TremoloSpeed {
            get {
                return ResourceManager.GetString("TremoloSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        public static string Triangle {
            get {
                return ResourceManager.GetString("Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbundle.
        /// </summary>
        public static string Unbundle {
            get {
                return ResourceManager.GetString("Unbundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underlying Patch.
        /// </summary>
        public static string UnderlyingPatch {
            get {
                return ResourceManager.GetString("UnderlyingPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underlying Patch ID.
        /// </summary>
        public static string UnderlyingPatchID {
            get {
                return ResourceManager.GetString("UnderlyingPatchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon Reset.
        /// </summary>
        public static string UponReset {
            get {
                return ResourceManager.GetString("UponReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrato Depth.
        /// </summary>
        public static string VibratoDepth {
            get {
                return ResourceManager.GetString("VibratoDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrato Speed.
        /// </summary>
        public static string VibratoSpeed {
            get {
                return ResourceManager.GetString("VibratoSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumes.
        /// </summary>
        public static string Volumes {
            get {
                return ResourceManager.GetString("Volumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAV File.
        /// </summary>
        public static string Wav {
            get {
                return ResourceManager.GetString("Wav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
