namespace JJ.Business.Synthesizer.Enums
{
    public enum DimensionEnum
    {
        Undefined = 0,
        Signal = 1,
        Frequency = 2,
        Volume = 3,
        Frequencies = 4,
        Volumes = 5,
        VibratoSpeed = 6,
        VibratoDepth = 7,
        TremoloSpeed = 8,
        TremoloDepth = 9,
        NoteDuration = 10,
        AttackDuration = 11,
        ReleaseDuration = 12,
        NoteStart = 13,
        Brightness = 14,
        Intensity = 15,
        BrightnessModulationSpeed = 16,
        BrightnessModulationDepth = 17,
        IntensityModulationSpeed = 18,
        IntensityModulationDepth = 19,
        DecayDuration = 20,
        SustainVolume = 21,
        Time = 22,
        Channel = 23,
        Harmonic = 24,
        Balance = 25,
        Sound = 26,
        Phase = 27,
        PreviousPosition = 28,
        Origin = 29,
        Input = 30,
        Result = 31,
        A = 32,
        B = 33,
        Base = 36,
        Exponent = 37,
        Difference = 38,
        Factor = 39,
        SamplingRate = 40,
        Start = 41,
        End = 42,
        Low = 43,
        High = 44,
        Ratio = 45,
        PitchBend = 46,
        MainVolume = 47
    }
}