using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using JJ.Business.Synthesizer.Wishes.NoteWishes;

// ReSharper disable once CheckNamespace
namespace JJ.Business.Synthesizer.Wishes
{
    public partial class SynthWishes
    {
        public FlowNode A_Minus1 => _[Notes.A_Minus1];
        public FlowNode A_Minus1_Sharp => _[Notes.A_Minus1_Sharp];
        public FlowNode B_Minus1 => _[Notes.B_Minus1];
        public FlowNode C0  => _[Notes.C0 ];
        public FlowNode Cs0 => _[Notes.Cs0];
        public FlowNode D0  => _[Notes.D0 ];
        public FlowNode Ds0 => _[Notes.Ds0];
        public FlowNode E0  => _[Notes.E0 ];
        public FlowNode F0  => _[Notes.F0 ];
        public FlowNode Fs0 => _[Notes.Fs0];
        public FlowNode G0  => _[Notes.G0 ];
        public FlowNode Gs0 => _[Notes.Gs0];
        public FlowNode A0  => _[Notes.A0 ];
        public FlowNode As0 => _[Notes.As0];
        public FlowNode B0  => _[Notes.B0 ];
        public FlowNode C1  => _[Notes.C1 ];
        public FlowNode Cs1 => _[Notes.Cs1];
        public FlowNode D1  => _[Notes.D1 ];
        public FlowNode Ds1 => _[Notes.Ds1];
        public FlowNode E1  => _[Notes.E1 ];
        public FlowNode F1  => _[Notes.F1 ];
        public FlowNode Fs1 => _[Notes.Fs1];
        public FlowNode G1  => _[Notes.G1 ];
        public FlowNode Gs1 => _[Notes.Gs1];
        public FlowNode A1  => _[Notes.A1 ];
        public FlowNode As1 => _[Notes.As1];
        public FlowNode B1  => _[Notes.B1 ];
        public FlowNode C2  => _[Notes.C2 ];
        public FlowNode Cs2 => _[Notes.Cs2];
        public FlowNode D2  => _[Notes.D2 ];
        public FlowNode Ds2 => _[Notes.Ds2];
        public FlowNode E2  => _[Notes.E2 ];
        public FlowNode F2  => _[Notes.F2 ];
        public FlowNode Fs2 => _[Notes.Fs2];
        public FlowNode G2  => _[Notes.G2 ];
        public FlowNode Gs2 => _[Notes.Gs2];
        public FlowNode A2  => _[Notes.A2 ];
        public FlowNode As2 => _[Notes.As2];
        public FlowNode B2  => _[Notes.B2 ];
        public FlowNode C3  => _[Notes.C3 ];
        public FlowNode Cs3 => _[Notes.Cs3];
        public FlowNode D3  => _[Notes.D3 ];
        public FlowNode Ds3 => _[Notes.Ds3];
        public FlowNode E3  => _[Notes.E3 ];
        public FlowNode F3  => _[Notes.F3 ];
        public FlowNode Fs3 => _[Notes.Fs3];
        public FlowNode G3  => _[Notes.G3 ];
        public FlowNode Gs3 => _[Notes.Gs3];
        public FlowNode A3  => _[Notes.A3 ];
        public FlowNode As3 => _[Notes.As3];
        public FlowNode B3  => _[Notes.B3 ];
        public FlowNode C4  => _[Notes.C4 ];
        public FlowNode Cs4 => _[Notes.Cs4];
        public FlowNode D4  => _[Notes.D4 ];
        public FlowNode Ds4 => _[Notes.Ds4];
        public FlowNode E4  => _[Notes.E4 ];
        public FlowNode F4  => _[Notes.F4 ];
        public FlowNode Fs4 => _[Notes.Fs4];
        public FlowNode G4  => _[Notes.G4 ];
        public FlowNode Gs4 => _[Notes.Gs4];
        public FlowNode A4  => _[Notes.A4 ];
        public FlowNode As4 => _[Notes.As4];
        public FlowNode B4  => _[Notes.B4 ];
        public FlowNode C5  => _[Notes.C5 ];
        public FlowNode Cs5 => _[Notes.Cs5];
        public FlowNode D5  => _[Notes.D5 ];
        public FlowNode Ds5 => _[Notes.Ds5];
        public FlowNode E5  => _[Notes.E5 ];
        public FlowNode F5  => _[Notes.F5 ];
        public FlowNode Fs5 => _[Notes.Fs5];
        public FlowNode G5  => _[Notes.G5 ];
        public FlowNode Gs5 => _[Notes.Gs5];
        public FlowNode A5  => _[Notes.A5 ];
        public FlowNode As5 => _[Notes.As5];
        public FlowNode B5  => _[Notes.B5 ];
        public FlowNode C6  => _[Notes.C6 ];
        public FlowNode Cs6 => _[Notes.Cs6];
        public FlowNode D6  => _[Notes.D6 ];
        public FlowNode Ds6 => _[Notes.Ds6];
        public FlowNode E6  => _[Notes.E6 ];
        public FlowNode F6  => _[Notes.F6 ];
        public FlowNode Fs6 => _[Notes.Fs6];
        public FlowNode G6  => _[Notes.G6 ];
        public FlowNode Gs6 => _[Notes.Gs6];
        public FlowNode A6  => _[Notes.A6 ];
        public FlowNode As6 => _[Notes.As6];
        public FlowNode B6  => _[Notes.B6 ];
        public FlowNode C7  => _[Notes.C7 ];
        public FlowNode Cs7 => _[Notes.Cs7];
        public FlowNode D7  => _[Notes.D7 ];
        public FlowNode Ds7 => _[Notes.Ds7];
        public FlowNode E7  => _[Notes.E7 ];
        public FlowNode F7  => _[Notes.F7 ];
        public FlowNode Fs7 => _[Notes.Fs7];
        public FlowNode G7  => _[Notes.G7 ];
        public FlowNode Gs7 => _[Notes.Gs7];
        public FlowNode A7  => _[Notes.A7 ];
        public FlowNode As7 => _[Notes.As7];
        public FlowNode B7  => _[Notes.B7 ];
        public FlowNode C8  => _[Notes.C8 ];
        public FlowNode Cs8 => _[Notes.Cs8];
        public FlowNode D8  => _[Notes.D8 ];
        public FlowNode Ds8 => _[Notes.Ds8];
        public FlowNode E8  => _[Notes.E8 ];
        public FlowNode F8  => _[Notes.F8 ];
        public FlowNode Fs8 => _[Notes.Fs8];
        public FlowNode G8  => _[Notes.G8 ];
        public FlowNode Gs8 => _[Notes.Gs8];
        public FlowNode A8  => _[Notes.A8 ];
        public FlowNode As8 => _[Notes.As8];
        public FlowNode B8  => _[Notes.B8 ];
        public FlowNode C9  => _[Notes.C9 ];
        public FlowNode Cs9 => _[Notes.Cs9];
        public FlowNode D9  => _[Notes.D9 ];
        public FlowNode Ds9 => _[Notes.Ds9];
        public FlowNode E9  => _[Notes.E9 ];
        public FlowNode F9  => _[Notes.F9 ];
        public FlowNode Fs9 => _[Notes.Fs9];
        public FlowNode G9  => _[Notes.G9 ];
        public FlowNode Gs9 => _[Notes.Gs9];

        public FlowNode SemiToneFactor => _[Notes.SemiToneFactor];
    }
}
