global using System;
global using System.Collections.Generic;
global using System.Reflection;
global using JJ.Framework.Common.Legacy;
global using JJ.Framework.Reflection;
global using JJ.Framework.Reflection.Core;
global using JJ.Persistence.Synthesizer;
global using JJ.Business.Synthesizer.Managers;
global using JJ.Business.Synthesizer.Structs;
global using static JJ.Business.Synthesizer.Wishes.NameWishes;
